name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dashboard/backend/requirements.txt

    - name: Run tests (if any)
      run: echo "No tests defined yet. Add your test command here."

    - name: Build/Package (if applicable)
      run: echo "No build steps defined yet. Add your build command here."